export enum StorageActionTypes {
  GET_USER_STORAGE_REQUEST = 'GET_USER_DATA_REQUEST',
  GET_USER_STORAGE_SUCCESS = 'GET_USER_DATA_REQUEST',
  GET_USER_STORAGE_FAILURE = 'GET_USER_DATA_REQUEST',
}

export enum AppActionTypes {
  GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS = 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_FAILURE = 'GET_USER_DATA_REQUEST',
}

export enum ItemActionTypes {
}